### ISSUE TITLE
Popup error message.

### ISSUE THREAD

**Issue by JohnChang08** [brunojensen/xmpp-chatbot#1]
I'm running this program within a configuration file, following with several errors but should be finished.
But later, "Timeout while waiting on advertised authentication mechanisms." pops.
And I couldn't find any clue of it.
My configuration file would be like below,
<
br.com.bea.chatbot.watson.username = a4e049a3-4307-4692-xxxxxxxxxxxxxxxxxxx
br.com.bea.chatbot.watson.password = xxxxxxxxxxxx
br.com.bea.chatbot.watson.workspace = Watson Assistant-xx
br.com.bea.chatbot.xmpp.username = ub02
br.com.bea.chatbot.xmpp.password = admin123!
br.com.bea.chatbot.xmpp.host = xxxxx.xxx
br.com.bea.chatbot.xmpp.port= 5280
>

Thank you!

**Comment by brunojensen** [comment]
Sorry for the delay - I didn't received any notification from github. Well, as you can see this is a immature project with no releases since the start. I was planning to do some maintenance but I couldn't find time, unfortunately.

So, hoping you already solve this or moved on to a better project, what I can say is that it's looks like an infrastructure problem, or some issue related with the xmpp lib (currently I'm using babber). Please check the like bellow.

https://bitbucket.org/sco0ter/babbler/issues/99/timeout-on-resource-binding-feature-when

I'll let you know whether I'll keep the project or not... but feel free to fork and change as you wish.
thanks for your contribution.
